name: derm_ai_scan

description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: #^11.2.5
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.1
  flutter_svg:
  image_picker: ^0.8.9
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  flutter_tflite:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
